### ISSUE TITLE
Add error handling to extract_features to prevent crashes

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#117]
I'm working on getting the trouble videos that can help for testing purposes, but currently if there is a problem with the extraction of a video - the whole script crashes entirely and needs to be restarted. This is super annoying when processing a large amount of videos over the course of days.

A few examples of errors we've run across:

`
Traceback (most recent call last):
  File "extract_features.py", line 132, in <module>
    main()
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "extract_features.py", line 85, in main
    extractor.start(batch_size=16,cores=4)
  File "/project/winnow/feature_extraction/intermediate_cnn.py", line 12, in start
    start_video_extraction(self.video_src,self.output_path,batch_sz=batch_size,cores=cores)
  File "/project/winnow/feature_extraction/extraction_routine.py", line 90, in start_video_extraction
    feature_extraction_videos(model, cores, batch_sz, video_list, output_path)
  File "/project/winnow/feature_extraction/extraction_routine.py", line 58, in feature_extraction_videos
    video_tensor = future_videos[video].get()
  File "/anaconda/envs/winnow/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'array([[[[0, 0, 0],...[0, 0, 0]]]], dtype=uint8)'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647",)'
`

Also (first part of stack trace is the same):
 Reason: 'OverflowError('cannot serialize a bytes object larger than 4 GiB',)'

**Comment by johnhbenetech** [comment]
@fsbatista i'm trying to track down the specifics, but my gut says this is related to duration of the video. I was able to reproduce by making like a 5 hour video (which failed) then reducing the sampling rate to frame/2sec and then it succeeded. My assumption is it's something to do with trying to pickle the frame_level output

Is there some error catching we could put in at the top level that can catch "any" error, log it, and move to the next one?

**Comment by fsbatista** [comment]
I'll have a look at it. Should be simple. Just want to see if any unwanted effects will occur because of it.
