### ISSUE TITLE
video signature extraction error

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#280]
Report from partner:
*Extracting Signatures from Video representations** **Traceback (most recent call last):**
**  File extract_features.py", line 81, in <module>**
**    video_signatures = sm.predict(VIDEO_LEVEL_SAVE_FOLDER)**
**  File "/project/winnow/feature_extraction/similarity_model.py", line 26, in predict**
**    self.build_features()**
**  File "/project/winnow/feature_extraction/similarity_model.py", line 44, in build_features**
**    self.features.append(np.load(vid)[0])**
**IndexError: index 0 is out of bounds for axis 0 with size 0*

**Comment by fsbatista** [comment]
Can you confirm which version the partner is working with? That seems to be fairly outdated. In any case, that error is usually related to the model not being able to find any videos to process (or the failure to find intermediate representations in the output folder).
