### ISSUE TITLE
windows install (non docker) fails to extract features. module cannot be found

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#3]
The following steps are performed on a clean install:

conda env create -f environment-windows.yaml

conda activate winnow

These steps complete sucessfully.

When running extract_features.py, i get the following error:

```
Traceback (most recent call last):
  File "extract_features.py", line 4, in <module>
    from winnow.feature_extraction import IntermediateCnnExtractor,frameToVideoRepresentation,SimilarityModel
  File "D:\CCSIDev\VideoDeduplication\winnow\__init__.py", line 1, in <module>
    from . import  feature_extraction
  File "D:\CCSIDev\VideoDeduplication\winnow\feature_extraction\__init__.py", line 2, in <module>
    from .frame_to_video import *
  File "D:\CCSIDev\VideoDeduplication\winnow\feature_extraction\frame_to_video.py", line 1, in <module>
    from .loading_utils import frame_to_global
  File "D:\CCSIDev\VideoDeduplication\winnow\feature_extraction\loading_utils.py", line 5, in <module>
    import matplotlib.pylab as plt
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\pylab.py", line 252, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:\Conda\envs\winnow\lib\site-packages\matplotlib\backends\qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by johnhbenetech** [comment]
seems to be resolved through

pip install pyqt5
