### ISSUE TITLE
Document remote fingerprint flow, investigate possible issue with contributor synching?

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#324]
Can we create a wiki page which documents the entire end to end flow of remote repo creation, partner creation, fingerprint push, fingerprint pull, matching. This should include the repo-admin commands as well as the commands needed for a theoretical partner user.

As you so this, I ran into an issue with contributor fetching. As you write documentation check if you run into the same issue, and if not, hopefully the documentation will clear up what went wrong.

My steps:
- create repo and users using repo-admin
- as partner user, add repo using created user, just cli
- push fingerprints using just push (this works)
- attempt to pull fingerprints using just pull --repo=XX

The pull command errors out (i dont have the exact error handy, but essentially it amounts to there being no contributors in the contributor table). I confirm this by directly querying the table. So for some reason the contributors arent being initialized.

**Comment by johnhbenetech** [comment]
```
Traceback (most recent call last):
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1609, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 972, in _init_compiled
    self.compiled_parameters[0]
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1172, in _process_parameters_for_postcompile
    for i, tuple_element in enumerate(values, 1)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1175, in <genexpr>
    and processors[name][j - 1] is not None
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda/envs/winnow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/winnow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/project/cli/cli/main.py", line 6, in <module>
    fire.Fire(RootCli, name="just")
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/project/cli/cli/handlers/errors.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "/project/cli/cli/handlers/root.py", line 48, in pull
    connector.pull_all(chunk_size=chunk_size, progress=ProgressBar(file=sys.stdout, unit="fingerprints"))
  File "/project/winnow/remote/connect.py", line 63, in pull_all
    self.store_remote_fingerprints(session=session, repo=repo, fingerprints=fingerprints)
  File "/project/winnow/remote/connect.py", line 94, in store_remote_fingerprints
    contributors = DatabaseConnector._get_or_create_contributors(session, repo, fingerprints)
  File "/project/winnow/remote/connect.py", line 113, in _get_or_create_contributors
    tuple_(Contributor.name).in_(contributor_names),
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2656, in all
    return self._iter().all()
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2794, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1653, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1615, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1609, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 972, in _init_compiled
    self.compiled_parameters[0]
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1172, in _process_parameters_for_postcompile
    for i, tuple_element in enumerate(values, 1)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1175, in <genexpr>
    and processors[name][j - 1] is not None
sqlalchemy.exc.StatementError: (builtins.IndexError) tuple index out of range
[SQL: SELECT contributors.id AS contributors_id, contributors.name AS contributors_name, contributors.repository_id AS contributors_repository_id 
FROM contributors 
WHERE %(param_1)s = contributors.repository_id AND (contributors.name) IN ([POSTCOMPILE_param_2])]
[parameters: [{}]]
  0%|         
```
