### ISSUE TITLE
Investigate broken import

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#465]
There seems to be an issue with the winnow import in: /development/security/__init__.py

When running the dockerized version, the server container immediately crashes with the following:

**Comment by johnhbenetech** [comment]
Reopening this as fix seemed to reveal another issue: 
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/server/server/main.py", line 6, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)`
