### ISSUE TITLE
Resolve AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#492]
Post installation local docker build of development branch, the videodeduplication container fails to start

```
Traceback (most recent call last):
  File "/anaconda/envs/winnow/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/notebook/notebookapp.py", line 60, in <module>
    from tornado import httpserver
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/tornado/httpserver.py", line 32, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/tornado/http1connection.py", line 32, in <module>
    from tornado import gen
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/tornado/gen.py", line 94, in <module>
    import contextvars
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/contextvars/_init_.py", line 4, in <module>
    import immutables
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/immutables/_init_.py", line 18, in <module>
    from ._protocols import MapKeys as MapKeys
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/immutables/_protocols.py", line 17, in <module>
    from typing_extensions import Protocol
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

**Comment by 13096676951x** [comment]
Hi, I also had this problem when running the code, did you solve it? Can you tell me how you solved this problem? Very grateful for your help

**Comment by stepan-anokhin** [comment]
> Hi, I also had this problem when running the code, did you solve it? Can you tell me how you solved this problem? Very grateful for your help

Hi @13096676951x ! It was fixed by downgrading `typing-extensions` package from 4.2.0 to 4.1.1. 

The root cause of the problem is that we use Python 3.6 but `typing-extensions` 4.2.0 requires Python >= 3.7. (while 4.1.1 requires Python >= 3.6). pip ignores the python version requirement and happily installs incompatible package.

**Comment by mufenglalala** [comment]
> 
 Could you please tell me how to downgrade? I run pip install typing_extensions==4.1.1 directly in cmd and it prompts that I can't find the relevant version.Thank you very much!
